import IfcElements from './IfcElements.js';
import {IfcAPI} from "web-ifc";

export class IfcUtils {
	static generateUUID() {
		const _lut = ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '0a', '0b', '0c', '0d', '0e', '0f', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '1a', '1b', '1c', '1d', '1e', '1f', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '2a', '2b', '2c', '2d', '2e', '2f', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '3a', '3b', '3c', '3d', '3e', '3f', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '4a', '4b', '4c', '4d', '4e', '4f', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '5a', '5b', '5c', '5d', '5e', '5f', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '6a', '6b', '6c', '6d', '6e', '6f', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '7a', '7b', '7c', '7d', '7e', '7f', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '8a', '8b', '8c', '8d', '8e', '8f', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '9a', '9b', '9c', '9d', '9e', '9f', 'a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'aa', 'ab', 'ac', 'ad', 'ae', 'af', 'b0', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9', 'ba', 'bb', 'bc', 'bd', 'be', 'bf', 'c0', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'ca', 'cb', 'cc', 'cd', 'ce', 'cf', 'd0', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8', 'd9', 'da', 'db', 'dc', 'dd', 'de', 'df', 'e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9', 'ea', 'eb', 'ec', 'ed', 'ee', 'ef', 'f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'fa', 'fb', 'fc', 'fd', 'fe', 'ff'];

		const d0 = Math.random() * 0xffffffff | 0;
		const d1 = Math.random() * 0xffffffff | 0;
		const d2 = Math.random() * 0xffffffff | 0;
		const d3 = Math.random() * 0xffffffff | 0;
		const uuid = _lut[d0 & 0xff] + _lut[d0 >> 8 & 0xff] + _lut[d0 >> 16 & 0xff] + _lut[d0 >> 24 & 0xff] + '-' +
			_lut[d1 & 0xff] + _lut[d1 >> 8 & 0xff] + '-' + _lut[d1 >> 16 & 0x0f | 0x40] + _lut[d1 >> 24 & 0xff] + '-' +
			_lut[d2 & 0x3f | 0x80] + _lut[d2 >> 8 & 0xff] + '-' + _lut[d2 >> 16 & 0xff] + _lut[d2 >> 24 & 0xff] +
			_lut[d3 & 0xff] + _lut[d3 >> 8 & 0xff] + _lut[d3 >> 16 & 0xff] + _lut[d3 >> 24 & 0xff];

		// .toLowerCase() here flattens concatenated strings to save heap memory space.
		return uuid.toLowerCase();
	}

	static generateIfcGUID(): string {
		// prettier-ignore
		const base64Chars = [
			"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "H",
			"I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
			"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r",
			"s", "t", "u", "v", "w", "x", "y", "z", "_", "$",
		];
		const guid = IfcUtils.generateUUID();
		const tailBytes = ((guid) => {
			const bytes = [];
			guid.split("-").map((number) => {
				const bytesInChar = number.match(/.{1,2}/g);
				if (bytesInChar) {
					return bytesInChar.map((byte) => bytes.push(parseInt(byte, 16)));
				}
				return null;
			});
			return bytes;
		})(guid);
		const headBytes = ((guid) => {
			const bytes = [];
			guid.split("-").map((number) => {
				const bytesInChar = number.match(/.{1,2}/g);
				if (bytesInChar) {
					return bytesInChar.map((byte) => bytes.push(byte));
				}
				return null;
			});
			return bytes;
		})(guid);
		const cvTo64 = (number, result, start, len) => {
			let num = number;
			const n = len;
			let i;
			for (i = 0; i < n; i += 1) {
				result[start + len - i - 1] =
					base64Chars[parseInt((num % 64).toString(), 10)];
				num /= 64;
			}
			return result;
		};
		const toUInt16 = (bytes, index) =>
			// eslint-disable-next-line no-bitwise
			parseInt(bytes.slice(index, index + 2).reduce((str, v) => str + v, ""), 16) >>> 0;
		const toUInt32 = (bytes, index) =>
			// eslint-disable-next-line no-bitwise
			parseInt(bytes.slice(index, index + 4).reduce((str, v) => str + v, ""), 16) >>> 0;
		const num = [];
		let str = [];
		let i;
		let n = 2;
		let pos = 0;
		num[0] = toUInt32(headBytes, 0) / 16777216;
		num[1] = toUInt32(headBytes, 0) % 16777216;
		// eslint-disable-next-line no-bitwise
		num[2] = (toUInt16(headBytes, 4) * 256 + toUInt16(headBytes, 6) / 256) >>> 0;
		num[3] =
			// eslint-disable-next-line no-bitwise
			((toUInt16(headBytes, 6) % 256) * 65536 +
				tailBytes[8] * 256 +
				tailBytes[9]) >>>
			0;
		// eslint-disable-next-line no-bitwise
		num[4] = (tailBytes[10] * 65536 + tailBytes[11] * 256 + tailBytes[12]) >>> 0;
		// eslint-disable-next-line no-bitwise
		num[5] = (tailBytes[13] * 65536 + tailBytes[14] * 256 + tailBytes[15]) >>> 0;
		for (i = 0; i < 6; i++) {
			str = cvTo64(num[i], str, pos, n);
			pos += n;
			n = 4;
		}
		return str.join("");
	}

	static getModelElements(ifcApi: IfcAPI, modelID: number = 0): number[] {
		const els: number[] = [];

		for (let x = 0; x < IfcElements.length; x++) {
			const type = IfcElements[x];
			const lines = ifcApi.GetLineIDsWithType(modelID, type);
			const size = lines.size();
			for (let y = 0; y < size; y++)
				els.push(lines.get(y))
		}
		return els;
	}

	static getModelElementsByCategory(ifcApi: any, category: any, modelID: number = 0): number[] {
		const els: number[] = [];

		const lines = ifcApi.GetLineIDsWithType(modelID, category);
		const size = lines.size();
		for (let y = 0; y < size; y++)
			els.push(lines.get(y));

		return els;
	}

	static getNameFromTypeCode(ifcApi: any, type: number): string {
		// Gets the name from a type code in camel case e.g. IfcSpace instead of IFCSPACE
		let name: string = ifcApi.GetNameFromTypeCode(type);
		if (IfcEntitiesMap[name]) name = IfcEntitiesMap[name];
		return name;
	}
}

const IfcEntitiesMap =  {
    IFCACTUATORTYPE: "IfcActuatorType",
    IFCADDRESS: "IfcAddress",
    IFCAIRTERMINALBOXTYPE: "IfcAirTerminalBoxType",
    IFCAIRTERMINALTYPE: "IfcAirTerminalType",
    IFCAIRTOAIRHEATRECOVERYTYPE: "IfcAirToAirHeatRecoveryType",
    IFCALARMTYPE: "IfcAlarmType",
    IFCANGULARDIMENSION: "IfcAngularDimension",
    IFCANNOTATION: "IfcAnnotation",
    IFCANNOTATIONCURVEOCCURRENCE: "IfcAnnotationCurveOccurrence",
    IFCANNOTATIONFILLAREA: "IfcAnnotationFillArea",
    IFCANNOTATIONFILLAREAOCCURRENCE: "IfcAnnotationFillAreaOccurrence",
    IFCANNOTATIONOCCURRENCE: "IfcAnnotationOccurrence",
    IFCANNOTATIONSURFACE: "IfcAnnotationSurface",
    IFCANNOTATIONSURFACEOCCURRENCE: "IfcAnnotationSurfaceOccurrence",
    IFCANNOTATIONSYMBOLOCCURRENCE: "IfcAnnotationSymbolOccurrence",
    IFCANNOTATIONTEXTOCCURRENCE: "IfcAnnotationTextOccurrence",
    IFCAPPLICATION: "IfcApplication",
    IFCAPPLIEDVALUE: "IfcAppliedValue",
    IFCAPPLIEDVALUERELATIONSHIP: "IfcAppliedValueRelationship",
    IFCAPPROVAL: "IfcApproval",
    IFCAPPROVALACTORRELATIONSHIP: "IfcApprovalActorRelationship",
    IFCAPPROVALPROPERTYRELATIONSHIP: "IfcApprovalPropertyRelationship",
    IFCAPPROVALRELATIONSHIP: "IfcApprovalRelationship",
    IFCARBITRARYCLOSEDPROFILEDEF: "IfcArbitraryClosedProfileDef",
    IFCARBITRARYOPENPROFILEDEF: "IfcArbitraryOpenProfileDef",
    IFCARBITRARYPROFILEDEFWITHVOIDS: "IfcArbitraryProfileDefWithVoids",
    IFCASSET: "IfcAsset",
    IFCASYMMETRICISHAPEPROFILEDEF: "IfcAsymmetricIShapeProfileDef",
    IFCAXIS1PLACEMENT: "IfcAxis1Placement",
    IFCAXIS2PLACEMENT2D: "IfcAxis2Placement2D",
    IFCAXIS2PLACEMENT3D: "IfcAxis2Placement3D",
    IFCBSPLINECURVE: "IfcBSplineCurve",
    IFCBEAM: "IfcBeam",
    IFCBEAMTYPE: "IfcBeamType",
    IFCBEZIERCURVE: "IfcBezierCurve",
    IFCBLOBTEXTURE: "IfcBlobTexture",
    IFCBLOCK: "IfcBlock",
    IFCBOILERTYPE: "IfcBoilerType",
    IFCBOOLEANCLIPPINGRESULT: "IfcBooleanClippingResult",
    IFCBOOLEANRESULT: "IfcBooleanResult",
    IFCBOUNDARYCONDITION: "IfcBoundaryCondition",
    IFCBOUNDARYEDGECONDITION: "IfcBoundaryEdgeCondition",
    IFCBOUNDARYFACECONDITION: "IfcBoundaryFaceCondition",
    IFCBOUNDARYNODECONDITION: "IfcBoundaryNodeCondition",
    IFCBOUNDARYNODECONDITIONWARPING: "IfcBoundaryNodeConditionWarping",
    IFCBOUNDEDCURVE: "IfcBoundedCurve",
    IFCBOUNDEDSURFACE: "IfcBoundedSurface",
    IFCBOUNDINGBOX: "IfcBoundingBox",
    IFCBOXEDHALFSPACE: "IfcBoxedHalfSpace",
    IFCBUILDING: "IfcBuilding",
    IFCBUILDINGELEMENT: "IfcBuildingElement",
    IFCBUILDINGELEMENTCOMPONENT: "IfcBuildingElementComponent",
    IFCBUILDINGELEMENTPART: "IfcBuildingElementPart",
    IFCBUILDINGELEMENTPROXY: "IfcBuildingElementProxy",
    IFCBUILDINGELEMENTPROXYTYPE: "IfcBuildingElementProxyType",
    IFCBUILDINGELEMENTTYPE: "IfcBuildingElementType",
    IFCBUILDINGSTOREY: "IfcBuildingStorey",
    IFCCSHAPEPROFILEDEF: "IfcCShapeProfileDef",
    IFCCABLECARRIERFITTINGTYPE: "IfcCableCarrierFittingType",
    IFCCABLECARRIERSEGMENTTYPE: "IfcCableCarrierSegmentType",
    IFCCABLESEGMENTTYPE: "IfcCableSegmentType",
    IFCCALENDARDATE: "IfcCalendarDate",
    IFCCARTESIANPOINT: "IfcCartesianPoint",
    IFCCARTESIANTRANSFORMATIONOPERATOR: "IfcCartesianTransformationOperator",
    IFCCARTESIANTRANSFORMATIONOPERATOR2D: "IfcCartesianTransformationOperator2D",
    IFCCARTESIANTRANSFORMATIONOPERATOR2DNONUNIFORM: "IfcCartesianTransformationOperator2DnonUniform",
    IFCCARTESIANTRANSFORMATIONOPERATOR3D: "IfcCartesianTransformationOperator3D",
    IFCCARTESIANTRANSFORMATIONOPERATOR3DNONUNIFORM: "IfcCartesianTransformationOperator3DnonUniform",
    IFCCENTERLINEPROFILEDEF: "IfcCenterLineProfileDef",
    IFCCHAMFEREDGEFEATURE: "IfcChamferEdgeFeature",
    IFCCHILLERTYPE: "IfcChillerType",
    IFCCIRCLE: "IfcCircle",
    IFCCIRCLEHOLLOWPROFILEDEF: "IfcCircleHollowProfileDef",
    IFCCIRCLEPROFILEDEF: "IfcCircleProfileDef",
    IFCCLASSIFICATION: "IfcClassification",
    IFCCLASSIFICATIONITEM: "IfcClassificationItem",
    IFCCLASSIFICATIONITEMRELATIONSHIP: "IfcClassificationItemRelationship",
    IFCCLASSIFICATIONNOTATION: "IfcClassificationNotation",
    IFCCLASSIFICATIONNOTATIONFACET: "IfcClassificationNotationFacet",
    IFCCLASSIFICATIONREFERENCE: "IfcClassificationReference",
    IFCCLOSEDSHELL: "IfcClosedShell",
    IFCCOILTYPE: "IfcCoilType",
    IFCCOLOURRGB: "IfcColourRgb",
    IFCCOLOURSPECIFICATION: "IfcColourSpecification",
    IFCCOLUMN: "IfcColumn",
    IFCCOLUMNTYPE: "IfcColumnType",
    IFCCOMPLEXPROPERTY: "IfcComplexProperty",
    IFCCOMPOSITECURVE: "IfcCompositeCurve",
    IFCCOMPOSITECURVESEGMENT: "IfcCompositeCurveSegment",
    IFCCOMPOSITEPROFILEDEF: "IfcCompositeProfileDef",
    IFCCOMPRESSORTYPE: "IfcCompressorType",
    IFCCONDENSERTYPE: "IfcCondenserType",
    IFCCONDITION: "IfcCondition",
    IFCCONDITIONCRITERION: "IfcConditionCriterion",
    IFCCONIC: "IfcConic",
    IFCCONNECTEDFACESET: "IfcConnectedFaceSet",
    IFCCONNECTIONCURVEGEOMETRY: "IfcConnectionCurveGeometry",
    IFCCONNECTIONGEOMETRY: "IfcConnectionGeometry",
    IFCCONNECTIONPOINTECCENTRICITY: "IfcConnectionPointEccentricity",
    IFCCONNECTIONPOINTGEOMETRY: "IfcConnectionPointGeometry",
    IFCCONNECTIONPORTGEOMETRY: "IfcConnectionPortGeometry",
    IFCCONNECTIONSURFACEGEOMETRY: "IfcConnectionSurfaceGeometry",
    IFCCONSTRAINT: "IfcConstraint",
    IFCCONSTRAINTAGGREGATIONRELATIONSHIP: "IfcConstraintAggregationRelationship",
    IFCCONSTRAINTCLASSIFICATIONRELATIONSHIP: "IfcConstraintClassificationRelationship",
    IFCCONSTRAINTRELATIONSHIP: "IfcConstraintRelationship",
    IFCCONSTRUCTIONEQUIPMENTRESOURCE: "IfcConstructionEquipmentResource",
    IFCCONSTRUCTIONMATERIALRESOURCE: "IfcConstructionMaterialResource",
    IFCCONSTRUCTIONPRODUCTRESOURCE: "IfcConstructionProductResource",
    IFCCONSTRUCTIONRESOURCE: "IfcConstructionResource",
    IFCCONTEXTDEPENDENTUNIT: "IfcContextDependentUnit",
    IFCCONTROL: "IfcControl",
    IFCCONTROLLERTYPE: "IfcControllerType",
    IFCCONVERSIONBASEDUNIT: "IfcConversionBasedUnit",
    IFCCOOLEDBEAMTYPE: "IfcCooledBeamType",
    IFCCOOLINGTOWERTYPE: "IfcCoolingTowerType",
    IFCCOORDINATEDUNIVERSALTIMEOFFSET: "IfcCoordinatedUniversalTimeOffset",
    IFCCOSTITEM: "IfcCostItem",
    IFCCOSTSCHEDULE: "IfcCostSchedule",
    IFCCOSTVALUE: "IfcCostValue",
    IFCCOVERING: "IfcCovering",
    IFCCOVERINGTYPE: "IfcCoveringType",
    IFCCRANERAILASHAPEPROFILEDEF: "IfcCraneRailAShapeProfileDef",
    IFCCRANERAILFSHAPEPROFILEDEF: "IfcCraneRailFShapeProfileDef",
    IFCCREWRESOURCE: "IfcCrewResource",
    IFCCSGPRIMITIVE3D: "IfcCsgPrimitive3D",
    IFCCSGSOLID: "IfcCsgSolid",
    IFCCURRENCYRELATIONSHIP: "IfcCurrencyRelationship",
    IFCCURTAINWALL: "IfcCurtainWall",
    IFCCURTAINWALLTYPE: "IfcCurtainWallType",
    IFCCURVE: "IfcCurve",
    IFCCURVEBOUNDEDPLANE: "IfcCurveBoundedPlane",
    IFCCURVESTYLE: "IfcCurveStyle",
    IFCCURVESTYLEFONT: "IfcCurveStyleFont",
    IFCCURVESTYLEFONTANDSCALING: "IfcCurveStyleFontAndScaling",
    IFCCURVESTYLEFONTPATTERN: "IfcCurveStyleFontPattern",
    IFCDAMPERTYPE: "IfcDamperType",
    IFCDATEANDTIME: "IfcDateAndTime",
    IFCDEFINEDSYMBOL: "IfcDefinedSymbol",
    IFCDERIVEDPROFILEDEF: "IfcDerivedProfileDef",
    IFCDERIVEDUNIT: "IfcDerivedUnit",
    IFCDERIVEDUNITELEMENT: "IfcDerivedUnitElement",
    IFCDIAMETERDIMENSION: "IfcDiameterDimension",
    IFCDIMENSIONCALLOUTRELATIONSHIP: "IfcDimensionCalloutRelationship",
    IFCDIMENSIONCURVE: "IfcDimensionCurve",
    IFCDIMENSIONCURVEDIRECTEDCALLOUT: "IfcDimensionCurveDirectedCallout",
    IFCDIMENSIONCURVETERMINATOR: "IfcDimensionCurveTerminator",
    IFCDIMENSIONPAIR: "IfcDimensionPair",
    IFCDIMENSIONALEXPONENTS: "IfcDimensionalExponents",
    IFCDIRECTION: "IfcDirection",
    IFCDISCRETEACCESSORY: "IfcDiscreteAccessory",
    IFCDISCRETEACCESSORYTYPE: "IfcDiscreteAccessoryType",
    IFCDISTRIBUTIONCHAMBERELEMENT: "IfcDistributionChamberElement",
    IFCDISTRIBUTIONCHAMBERELEMENTTYPE: "IfcDistributionChamberElementType",
    IFCDISTRIBUTIONCONTROLELEMENT: "IfcDistributionControlElement",
    IFCDISTRIBUTIONCONTROLELEMENTTYPE: "IfcDistributionControlElementType",
    IFCDISTRIBUTIONELEMENT: "IfcDistributionElement",
    IFCDISTRIBUTIONELEMENTTYPE: "IfcDistributionElementType",
    IFCDISTRIBUTIONFLOWELEMENT: "IfcDistributionFlowElement",
    IFCDISTRIBUTIONFLOWELEMENTTYPE: "IfcDistributionFlowElementType",
    IFCDISTRIBUTIONPORT: "IfcDistributionPort",
    IFCDOCUMENTELECTRONICFORMAT: "IfcDocumentElectronicFormat",
    IFCDOCUMENTINFORMATION: "IfcDocumentInformation",
    IFCDOCUMENTINFORMATIONRELATIONSHIP: "IfcDocumentInformationRelationship",
    IFCDOCUMENTREFERENCE: "IfcDocumentReference",
    IFCDOOR: "IfcDoor",
    IFCDOORLININGPROPERTIES: "IfcDoorLiningProperties",
    IFCDOORPANELPROPERTIES: "IfcDoorPanelProperties",
    IFCDOORSTYLE: "IfcDoorStyle",
    IFCDRAUGHTINGCALLOUT: "IfcDraughtingCallout",
    IFCDRAUGHTINGCALLOUTRELATIONSHIP: "IfcDraughtingCalloutRelationship",
    IFCDRAUGHTINGPREDEFINEDCOLOUR: "IfcDraughtingPreDefinedColour",
    IFCDRAUGHTINGPREDEFINEDCURVEFONT: "IfcDraughtingPreDefinedCurveFont",
    IFCDRAUGHTINGPREDEFINEDTEXTFONT: "IfcDraughtingPreDefinedTextFont",
    IFCDUCTFITTINGTYPE: "IfcDuctFittingType",
    IFCDUCTSEGMENTTYPE: "IfcDuctSegmentType",
    IFCDUCTSILENCERTYPE: "IfcDuctSilencerType",
    IFCEDGE: "IfcEdge",
    IFCEDGECURVE: "IfcEdgeCurve",
    IFCEDGEFEATURE: "IfcEdgeFeature",
    IFCEDGELOOP: "IfcEdgeLoop",
    IFCELECTRICAPPLIANCETYPE: "IfcElectricApplianceType",
    IFCELECTRICDISTRIBUTIONPOINT: "IfcElectricDistributionPoint",
    IFCELECTRICFLOWSTORAGEDEVICETYPE: "IfcElectricFlowStorageDeviceType",
    IFCELECTRICGENERATORTYPE: "IfcElectricGeneratorType",
    IFCELECTRICHEATERTYPE: "IfcElectricHeaterType",
    IFCELECTRICMOTORTYPE: "IfcElectricMotorType",
    IFCELECTRICTIMECONTROLTYPE: "IfcElectricTimeControlType",
    IFCELECTRICALBASEPROPERTIES: "IfcElectricalBaseProperties",
    IFCELECTRICALCIRCUIT: "IfcElectricalCircuit",
    IFCELECTRICALELEMENT: "IfcElectricalElement",
    IFCELEMENT: "IfcElement",
    IFCELEMENTASSEMBLY: "IfcElementAssembly",
    IFCELEMENTCOMPONENT: "IfcElementComponent",
    IFCELEMENTCOMPONENTTYPE: "IfcElementComponentType",
    IFCELEMENTQUANTITY: "IfcElementQuantity",
    IFCELEMENTTYPE: "IfcElementType",
    IFCELEMENTARYSURFACE: "IfcElementarySurface",
    IFCELLIPSE: "IfcEllipse",
    IFCELLIPSEPROFILEDEF: "IfcEllipseProfileDef",
    IFCENERGYCONVERSIONDEVICE: "IfcEnergyConversionDevice",
    IFCENERGYCONVERSIONDEVICETYPE: "IfcEnergyConversionDeviceType",
    IFCENERGYPROPERTIES: "IfcEnergyProperties",
    IFCENVIRONMENTALIMPACTVALUE: "IfcEnvironmentalImpactValue",
    IFCEQUIPMENTELEMENT: "IfcEquipmentElement",
    IFCEQUIPMENTSTANDARD: "IfcEquipmentStandard",
    IFCEVAPORATIVECOOLERTYPE: "IfcEvaporativeCoolerType",
    IFCEVAPORATORTYPE: "IfcEvaporatorType",
    IFCEXTENDEDMATERIALPROPERTIES: "IfcExtendedMaterialProperties",
    IFCEXTERNALREFERENCE: "IfcExternalReference",
    IFCEXTERNALLYDEFINEDHATCHSTYLE: "IfcExternallyDefinedHatchStyle",
    IFCEXTERNALLYDEFINEDSURFACESTYLE: "IfcExternallyDefinedSurfaceStyle",
    IFCEXTERNALLYDEFINEDSYMBOL: "IfcExternallyDefinedSymbol",
    IFCEXTERNALLYDEFINEDTEXTFONT: "IfcExternallyDefinedTextFont",
    IFCEXTRUDEDAREASOLID: "IfcExtrudedAreaSolid",
    IFCFACE: "IfcFace",
    IFCFACEBASEDSURFACEMODEL: "IfcFaceBasedSurfaceModel",
    IFCFACEBOUND: "IfcFaceBound",
    IFCFACEOUTERBOUND: "IfcFaceOuterBound",
    IFCFACESURFACE: "IfcFaceSurface",
    IFCFACETEDBREP: "IfcFacetedBrep",
    IFCFACETEDBREPWITHVOIDS: "IfcFacetedBrepWithVoids",
    IFCFAILURECONNECTIONCONDITION: "IfcFailureConnectionCondition",
    IFCFANTYPE: "IfcFanType",
    IFCFASTENER: "IfcFastener",
    IFCFASTENERTYPE: "IfcFastenerType",
    IFCFEATUREELEMENT: "IfcFeatureElement",
    IFCFEATUREELEMENTADDITION: "IfcFeatureElementAddition",
    IFCFEATUREELEMENTSUBTRACTION: "IfcFeatureElementSubtraction",
    IFCFILLAREASTYLE: "IfcFillAreaStyle",
    IFCFILLAREASTYLEHATCHING: "IfcFillAreaStyleHatching",
    IFCFILLAREASTYLETILESYMBOLWITHSTYLE: "IfcFillAreaStyleTileSymbolWithStyle",
    IFCFILLAREASTYLETILES: "IfcFillAreaStyleTiles",
    IFCFILTERTYPE: "IfcFilterType",
    IFCFIRESUPPRESSIONTERMINALTYPE: "IfcFireSuppressionTerminalType",
    IFCFLOWCONTROLLER: "IfcFlowController",
    IFCFLOWCONTROLLERTYPE: "IfcFlowControllerType",
    IFCFLOWFITTING: "IfcFlowFitting",
    IFCFLOWFITTINGTYPE: "IfcFlowFittingType",
    IFCFLOWINSTRUMENTTYPE: "IfcFlowInstrumentType",
    IFCFLOWMETERTYPE: "IfcFlowMeterType",
    IFCFLOWMOVINGDEVICE: "IfcFlowMovingDevice",
    IFCFLOWMOVINGDEVICETYPE: "IfcFlowMovingDeviceType",
    IFCFLOWSEGMENT: "IfcFlowSegment",
    IFCFLOWSEGMENTTYPE: "IfcFlowSegmentType",
    IFCFLOWSTORAGEDEVICE: "IfcFlowStorageDevice",
    IFCFLOWSTORAGEDEVICETYPE: "IfcFlowStorageDeviceType",
    IFCFLOWTERMINAL: "IfcFlowTerminal",
    IFCFLOWTERMINALTYPE: "IfcFlowTerminalType",
    IFCFLOWTREATMENTDEVICE: "IfcFlowTreatmentDevice",
    IFCFLOWTREATMENTDEVICETYPE: "IfcFlowTreatmentDeviceType",
    IFCFLUIDFLOWPROPERTIES: "IfcFluidFlowProperties",
    IFCFOOTING: "IfcFooting",
    IFCFUELPROPERTIES: "IfcFuelProperties",
    IFCFURNISHINGELEMENT: "IfcFurnishingElement",
    IFCFURNISHINGELEMENTTYPE: "IfcFurnishingElementType",
    IFCFURNITURESTANDARD: "IfcFurnitureStandard",
    IFCFURNITURETYPE: "IfcFurnitureType",
    IFCGASTERMINALTYPE: "IfcGasTerminalType",
    IFCGENERALMATERIALPROPERTIES: "IfcGeneralMaterialProperties",
    IFCGENERALPROFILEPROPERTIES: "IfcGeneralProfileProperties",
    IFCGEOMETRICCURVESET: "IfcGeometricCurveSet",
    IFCGEOMETRICREPRESENTATIONCONTEXT: "IfcGeometricRepresentationContext",
    IFCGEOMETRICREPRESENTATIONITEM: "IfcGeometricRepresentationItem",
    IFCGEOMETRICREPRESENTATIONSUBCONTEXT: "IfcGeometricRepresentationSubContext",
    IFCGEOMETRICSET: "IfcGeometricSet",
    IFCGRID: "IfcGrid",
    IFCGRIDAXIS: "IfcGridAxis",
    IFCGRIDPLACEMENT: "IfcGridPlacement",
    IFCGROUP: "IfcGroup",
    IFCHALFSPACESOLID: "IfcHalfSpaceSolid",
    IFCHEATEXCHANGERTYPE: "IfcHeatExchangerType",
    IFCHUMIDIFIERTYPE: "IfcHumidifierType",
    IFCHYGROSCOPICMATERIALPROPERTIES: "IfcHygroscopicMaterialProperties",
    IFCISHAPEPROFILEDEF: "IfcIShapeProfileDef",
    IFCIMAGETEXTURE: "IfcImageTexture",
    IFCINVENTORY: "IfcInventory",
    IFCIRREGULARTIMESERIES: "IfcIrregularTimeSeries",
    IFCIRREGULARTIMESERIESVALUE: "IfcIrregularTimeSeriesValue",
    IFCJUNCTIONBOXTYPE: "IfcJunctionBoxType",
    IFCLSHAPEPROFILEDEF: "IfcLShapeProfileDef",
    IFCLABORRESOURCE: "IfcLaborResource",
    IFCLAMPTYPE: "IfcLampType",
    IFCLIBRARYINFORMATION: "IfcLibraryInformation",
    IFCLIBRARYREFERENCE: "IfcLibraryReference",
    IFCLIGHTDISTRIBUTIONDATA: "IfcLightDistributionData",
    IFCLIGHTFIXTURETYPE: "IfcLightFixtureType",
    IFCLIGHTINTENSITYDISTRIBUTION: "IfcLightIntensityDistribution",
    IFCLIGHTSOURCE: "IfcLightSource",
    IFCLIGHTSOURCEAMBIENT: "IfcLightSourceAmbient",
    IFCLIGHTSOURCEDIRECTIONAL: "IfcLightSourceDirectional",
    IFCLIGHTSOURCEGONIOMETRIC: "IfcLightSourceGoniometric",
    IFCLIGHTSOURCEPOSITIONAL: "IfcLightSourcePositional",
    IFCLIGHTSOURCESPOT: "IfcLightSourceSpot",
    IFCLINE: "IfcLine",
    IFCLINEARDIMENSION: "IfcLinearDimension",
    IFCLOCALPLACEMENT: "IfcLocalPlacement",
    IFCLOCALTIME: "IfcLocalTime",
    IFCLOOP: "IfcLoop",
    IFCMANIFOLDSOLIDBREP: "IfcManifoldSolidBrep",
    IFCMAPPEDITEM: "IfcMappedItem",
    IFCMATERIAL: "IfcMaterial",
    IFCMATERIALCLASSIFICATIONRELATIONSHIP: "IfcMaterialClassificationRelationship",
    IFCMATERIALDEFINITIONREPRESENTATION: "IfcMaterialDefinitionRepresentation",
    IFCMATERIALLAYER: "IfcMaterialLayer",
    IFCMATERIALLAYERSET: "IfcMaterialLayerSet",
    IFCMATERIALLAYERSETUSAGE: "IfcMaterialLayerSetUsage",
    IFCMATERIALLIST: "IfcMaterialList",
    IFCMATERIALPROPERTIES: "IfcMaterialProperties",
    IFCMEASUREWITHUNIT: "IfcMeasureWithUnit",
    IFCMECHANICALCONCRETEMATERIALPROPERTIES: "IfcMechanicalConcreteMaterialProperties",
    IFCMECHANICALFASTENER: "IfcMechanicalFastener",
    IFCMECHANICALFASTENERTYPE: "IfcMechanicalFastenerType",
    IFCMECHANICALMATERIALPROPERTIES: "IfcMechanicalMaterialProperties",
    IFCMECHANICALSTEELMATERIALPROPERTIES: "IfcMechanicalSteelMaterialProperties",
    IFCMEMBER: "IfcMember",
    IFCMEMBERTYPE: "IfcMemberType",
    IFCMETRIC: "IfcMetric",
    IFCMONETARYUNIT: "IfcMonetaryUnit",
    IFCMOTORCONNECTIONTYPE: "IfcMotorConnectionType",
    IFCMOVE: "IfcMove",
    IFCNAMEDUNIT: "IfcNamedUnit",
    IFCOBJECT: "IfcObject",
    IFCOBJECTDEFINITION: "IfcObjectDefinition",
    IFCOBJECTPLACEMENT: "IfcObjectPlacement",
    IFCOBJECTIVE: "IfcObjective",
    IFCOCCUPANT: "IfcOccupant",
    IFCOFFSETCURVE2D: "IfcOffsetCurve2D",
    IFCOFFSETCURVE3D: "IfcOffsetCurve3D",
    IFCONEDIRECTIONREPEATFACTOR: "IfcOneDirectionRepeatFactor",
    IFCOPENSHELL: "IfcOpenShell",
    IFCOPENINGELEMENT: "IfcOpeningElement",
    IFCOPTICALMATERIALPROPERTIES: "IfcOpticalMaterialProperties",
    IFCORDERACTION: "IfcOrderAction",
    IFCORGANIZATION: "IfcOrganization",
    IFCORGANIZATIONRELATIONSHIP: "IfcOrganizationRelationship",
    IFCORIENTEDEDGE: "IfcOrientedEdge",
    IFCOUTLETTYPE: "IfcOutletType",
    IFCOWNERHISTORY: "IfcOwnerHistory",
    IFCPARAMETERIZEDPROFILEDEF: "IfcParameterizedProfileDef",
    IFCPATH: "IfcPath",
    IFCPERFORMANCEHISTORY: "IfcPerformanceHistory",
    IFCPERMEABLECOVERINGPROPERTIES: "IfcPermeableCoveringProperties",
    IFCPERMIT: "IfcPermit",
    IFCPERSON: "IfcPerson",
    IFCPERSONANDORGANIZATION: "IfcPersonAndOrganization",
    IFCPHYSICALCOMPLEXQUANTITY: "IfcPhysicalComplexQuantity",
    IFCPHYSICALQUANTITY: "IfcPhysicalQuantity",
    IFCPHYSICALSIMPLEQUANTITY: "IfcPhysicalSimpleQuantity",
    IFCPILE: "IfcPile",
    IFCPIPEFITTINGTYPE: "IfcPipeFittingType",
    IFCPIPESEGMENTTYPE: "IfcPipeSegmentType",
    IFCPIXELTEXTURE: "IfcPixelTexture",
    IFCPLACEMENT: "IfcPlacement",
    IFCPLANARBOX: "IfcPlanarBox",
    IFCPLANAREXTENT: "IfcPlanarExtent",
    IFCPLANE: "IfcPlane",
    IFCPLATE: "IfcPlate",
    IFCPLATETYPE: "IfcPlateType",
    IFCPOINT: "IfcPoint",
    IFCPOINTONCURVE: "IfcPointOnCurve",
    IFCPOINTONSURFACE: "IfcPointOnSurface",
    IFCPOLYLOOP: "IfcPolyLoop",
    IFCPOLYGONALBOUNDEDHALFSPACE: "IfcPolygonalBoundedHalfSpace",
    IFCPOLYLINE: "IfcPolyline",
    IFCPORT: "IfcPort",
    IFCPOSTALADDRESS: "IfcPostalAddress",
    IFCPREDEFINEDCOLOUR: "IfcPreDefinedColour",
    IFCPREDEFINEDCURVEFONT: "IfcPreDefinedCurveFont",
    IFCPREDEFINEDDIMENSIONSYMBOL: "IfcPreDefinedDimensionSymbol",
    IFCPREDEFINEDITEM: "IfcPreDefinedItem",
    IFCPREDEFINEDPOINTMARKERSYMBOL: "IfcPreDefinedPointMarkerSymbol",
    IFCPREDEFINEDSYMBOL: "IfcPreDefinedSymbol",
    IFCPREDEFINEDTERMINATORSYMBOL: "IfcPreDefinedTerminatorSymbol",
    IFCPREDEFINEDTEXTFONT: "IfcPreDefinedTextFont",
    IFCPRESENTATIONLAYERASSIGNMENT: "IfcPresentationLayerAssignment",
    IFCPRESENTATIONLAYERWITHSTYLE: "IfcPresentationLayerWithStyle",
    IFCPRESENTATIONSTYLE: "IfcPresentationStyle",
    IFCPRESENTATIONSTYLEASSIGNMENT: "IfcPresentationStyleAssignment",
    IFCPROCEDURE: "IfcProcedure",
    IFCPROCESS: "IfcProcess",
    IFCPRODUCT: "IfcProduct",
    IFCPRODUCTDEFINITIONSHAPE: "IfcProductDefinitionShape",
    IFCPRODUCTREPRESENTATION: "IfcProductRepresentation",
    IFCPRODUCTSOFCOMBUSTIONPROPERTIES: "IfcProductsOfCombustionProperties",
    IFCPROFILEDEF: "IfcProfileDef",
    IFCPROFILEPROPERTIES: "IfcProfileProperties",
    IFCPROJECT: "IfcProject",
    IFCPROJECTORDER: "IfcProjectOrder",
    IFCPROJECTORDERRECORD: "IfcProjectOrderRecord",
    IFCPROJECTIONCURVE: "IfcProjectionCurve",
    IFCPROJECTIONELEMENT: "IfcProjectionElement",
    IFCPROPERTY: "IfcProperty",
    IFCPROPERTYBOUNDEDVALUE: "IfcPropertyBoundedValue",
    IFCPROPERTYCONSTRAINTRELATIONSHIP: "IfcPropertyConstraintRelationship",
    IFCPROPERTYDEFINITION: "IfcPropertyDefinition",
    IFCPROPERTYDEPENDENCYRELATIONSHIP: "IfcPropertyDependencyRelationship",
    IFCPROPERTYENUMERATEDVALUE: "IfcPropertyEnumeratedValue",
    IFCPROPERTYENUMERATION: "IfcPropertyEnumeration",
    IFCPROPERTYLISTVALUE: "IfcPropertyListValue",
    IFCPROPERTYREFERENCEVALUE: "IfcPropertyReferenceValue",
    IFCPROPERTYSET: "IfcPropertySet",
    IFCPROPERTYSETDEFINITION: "IfcPropertySetDefinition",
    IFCPROPERTYSINGLEVALUE: "IfcPropertySingleValue",
    IFCPROPERTYTABLEVALUE: "IfcPropertyTableValue",
    IFCPROTECTIVEDEVICETYPE: "IfcProtectiveDeviceType",
    IFCPROXY: "IfcProxy",
    IFCPUMPTYPE: "IfcPumpType",
    IFCQUANTITYAREA: "IfcQuantityArea",
    IFCQUANTITYCOUNT: "IfcQuantityCount",
    IFCQUANTITYLENGTH: "IfcQuantityLength",
    IFCQUANTITYTIME: "IfcQuantityTime",
    IFCQUANTITYVOLUME: "IfcQuantityVolume",
    IFCQUANTITYWEIGHT: "IfcQuantityWeight",
    IFCRADIUSDIMENSION: "IfcRadiusDimension",
    IFCRAILING: "IfcRailing",
    IFCRAILINGTYPE: "IfcRailingType",
    IFCRAMP: "IfcRamp",
    IFCRAMPFLIGHT: "IfcRampFlight",
    IFCRAMPFLIGHTTYPE: "IfcRampFlightType",
    IFCRATIONALBEZIERCURVE: "IfcRationalBezierCurve",
    IFCRECTANGLEHOLLOWPROFILEDEF: "IfcRectangleHollowProfileDef",
    IFCRECTANGLEPROFILEDEF: "IfcRectangleProfileDef",
    IFCRECTANGULARPYRAMID: "IfcRectangularPyramid",
    IFCRECTANGULARTRIMMEDSURFACE: "IfcRectangularTrimmedSurface",
    IFCREFERENCESVALUEDOCUMENT: "IfcReferencesValueDocument",
    IFCREGULARTIMESERIES: "IfcRegularTimeSeries",
    IFCREINFORCEMENTBARPROPERTIES: "IfcReinforcementBarProperties",
    IFCREINFORCEMENTDEFINITIONPROPERTIES: "IfcReinforcementDefinitionProperties",
    IFCREINFORCINGBAR: "IfcReinforcingBar",
    IFCREINFORCINGELEMENT: "IfcReinforcingElement",
    IFCREINFORCINGMESH: "IfcReinforcingMesh",
    IFCRELAGGREGATES: "IfcRelAggregates",
    IFCRELASSIGNS: "IfcRelAssigns",
    IFCRELASSIGNSTASKS: "IfcRelAssignsTasks",
    IFCRELASSIGNSTOACTOR: "IfcRelAssignsToActor",
    IFCRELASSIGNSTOCONTROL: "IfcRelAssignsToControl",
    IFCRELASSIGNSTOGROUP: "IfcRelAssignsToGroup",
    IFCRELASSIGNSTOPROCESS: "IfcRelAssignsToProcess",
    IFCRELASSIGNSTOPRODUCT: "IfcRelAssignsToProduct",
    IFCRELASSIGNSTOPROJECTORDER: "IfcRelAssignsToProjectOrder",
    IFCRELASSIGNSTORESOURCE: "IfcRelAssignsToResource",
    IFCRELASSOCIATES: "IfcRelAssociates",
    IFCRELASSOCIATESAPPLIEDVALUE: "IfcRelAssociatesAppliedValue",
    IFCRELASSOCIATESAPPROVAL: "IfcRelAssociatesApproval",
    IFCRELASSOCIATESCLASSIFICATION: "IfcRelAssociatesClassification",
    IFCRELASSOCIATESCONSTRAINT: "IfcRelAssociatesConstraint",
    IFCRELASSOCIATESDOCUMENT: "IfcRelAssociatesDocument",
    IFCRELASSOCIATESLIBRARY: "IfcRelAssociatesLibrary",
    IFCRELASSOCIATESMATERIAL: "IfcRelAssociatesMaterial",
    IFCRELASSOCIATESPROFILEPROPERTIES: "IfcRelAssociatesProfileProperties",
    IFCRELCONNECTS: "IfcRelConnects",
    IFCRELCONNECTSELEMENTS: "IfcRelConnectsElements",
    IFCRELCONNECTSPATHELEMENTS: "IfcRelConnectsPathElements",
    IFCRELCONNECTSPORTTOELEMENT: "IfcRelConnectsPortToElement",
    IFCRELCONNECTSPORTS: "IfcRelConnectsPorts",
    IFCRELCONNECTSSTRUCTURALACTIVITY: "IfcRelConnectsStructuralActivity",
    IFCRELCONNECTSSTRUCTURALELEMENT: "IfcRelConnectsStructuralElement",
    IFCRELCONNECTSSTRUCTURALMEMBER: "IfcRelConnectsStructuralMember",
    IFCRELCONNECTSWITHECCENTRICITY: "IfcRelConnectsWithEccentricity",
    IFCRELCONNECTSWITHREALIZINGELEMENTS: "IfcRelConnectsWithRealizingElements",
    IFCRELCONTAINEDINSPATIALSTRUCTURE: "IfcRelContainedInSpatialStructure",
    IFCRELCOVERSBLDGELEMENTS: "IfcRelCoversBldgElements",
    IFCRELCOVERSSPACES: "IfcRelCoversSpaces",
    IFCRELDECOMPOSES: "IfcRelDecomposes",
    IFCRELDEFINES: "IfcRelDefines",
    IFCRELDEFINESBYPROPERTIES: "IfcRelDefinesByProperties",
    IFCRELDEFINESBYTYPE: "IfcRelDefinesByType",
    IFCRELFILLSELEMENT: "IfcRelFillsElement",
    IFCRELFLOWCONTROLELEMENTS: "IfcRelFlowControlElements",
    IFCRELINTERACTIONREQUIREMENTS: "IfcRelInteractionRequirements",
    IFCRELNESTS: "IfcRelNests",
    IFCRELOCCUPIESSPACES: "IfcRelOccupiesSpaces",
    IFCRELOVERRIDESPROPERTIES: "IfcRelOverridesProperties",
    IFCRELPROJECTSELEMENT: "IfcRelProjectsElement",
    IFCRELREFERENCEDINSPATIALSTRUCTURE: "IfcRelReferencedInSpatialStructure",
    IFCRELSCHEDULESCOSTITEMS: "IfcRelSchedulesCostItems",
    IFCRELSEQUENCE: "IfcRelSequence",
    IFCRELSERVICESBUILDINGS: "IfcRelServicesBuildings",
    IFCRELSPACEBOUNDARY: "IfcRelSpaceBoundary",
    IFCRELVOIDSELEMENT: "IfcRelVoidsElement",
    IFCRELATIONSHIP: "IfcRelationship",
    IFCRELAXATION: "IfcRelaxation",
    IFCREPRESENTATION: "IfcRepresentation",
    IFCREPRESENTATIONCONTEXT: "IfcRepresentationContext",
    IFCREPRESENTATIONITEM: "IfcRepresentationItem",
    IFCREPRESENTATIONMAP: "IfcRepresentationMap",
    IFCRESOURCE: "IfcResource",
    IFCREVOLVEDAREASOLID: "IfcRevolvedAreaSolid",
    IFCRIBPLATEPROFILEPROPERTIES: "IfcRibPlateProfileProperties",
    IFCRIGHTCIRCULARCONE: "IfcRightCircularCone",
    IFCRIGHTCIRCULARCYLINDER: "IfcRightCircularCylinder",
    IFCROOF: "IfcRoof",
    IFCROOT: "IfcRoot",
    IFCROUNDEDEDGEFEATURE: "IfcRoundedEdgeFeature",
    IFCROUNDEDRECTANGLEPROFILEDEF: "IfcRoundedRectangleProfileDef",
    IFCSIUNIT: "IfcSIUnit",
    IFCSANITARYTERMINALTYPE: "IfcSanitaryTerminalType",
    IFCSCHEDULETIMECONTROL: "IfcScheduleTimeControl",
    IFCSECTIONPROPERTIES: "IfcSectionProperties",
    IFCSECTIONREINFORCEMENTPROPERTIES: "IfcSectionReinforcementProperties",
    IFCSECTIONEDSPINE: "IfcSectionedSpine",
    IFCSENSORTYPE: "IfcSensorType",
    IFCSERVICELIFE: "IfcServiceLife",
    IFCSERVICELIFEFACTOR: "IfcServiceLifeFactor",
    IFCSHAPEASPECT: "IfcShapeAspect",
    IFCSHAPEMODEL: "IfcShapeModel",
    IFCSHAPEREPRESENTATION: "IfcShapeRepresentation",
    IFCSHELLBASEDSURFACEMODEL: "IfcShellBasedSurfaceModel",
    IFCSIMPLEPROPERTY: "IfcSimpleProperty",
    IFCSITE: "IfcSite",
    IFCSLAB: "IfcSlab",
    IFCSLABTYPE: "IfcSlabType",
    IFCSLIPPAGECONNECTIONCONDITION: "IfcSlippageConnectionCondition",
    IFCSOLIDMODEL: "IfcSolidModel",
    IFCSOUNDPROPERTIES: "IfcSoundProperties",
    IFCSOUNDVALUE: "IfcSoundValue",
    IFCSPACE: "IfcSpace",
    IFCSPACEHEATERTYPE: "IfcSpaceHeaterType",
    IFCSPACEPROGRAM: "IfcSpaceProgram",
    IFCSPACETHERMALLOADPROPERTIES: "IfcSpaceThermalLoadProperties",
    IFCSPACETYPE: "IfcSpaceType",
    IFCSPATIALSTRUCTUREELEMENT: "IfcSpatialStructureElement",
    IFCSPATIALSTRUCTUREELEMENTTYPE: "IfcSpatialStructureElementType",
    IFCSPHERE: "IfcSphere",
    IFCSTACKTERMINALTYPE: "IfcStackTerminalType",
    IFCSTAIR: "IfcStair",
    IFCSTAIRFLIGHT: "IfcStairFlight",
    IFCSTAIRFLIGHTTYPE: "IfcStairFlightType",
    IFCSTRUCTURALACTION: "IfcStructuralAction",
    IFCSTRUCTURALACTIVITY: "IfcStructuralActivity",
    IFCSTRUCTURALANALYSISMODEL: "IfcStructuralAnalysisModel",
    IFCSTRUCTURALCONNECTION: "IfcStructuralConnection",
    IFCSTRUCTURALCONNECTIONCONDITION: "IfcStructuralConnectionCondition",
    IFCSTRUCTURALCURVECONNECTION: "IfcStructuralCurveConnection",
    IFCSTRUCTURALCURVEMEMBER: "IfcStructuralCurveMember",
    IFCSTRUCTURALCURVEMEMBERVARYING: "IfcStructuralCurveMemberVarying",
    IFCSTRUCTURALITEM: "IfcStructuralItem",
    IFCSTRUCTURALLINEARACTION: "IfcStructuralLinearAction",
    IFCSTRUCTURALLINEARACTIONVARYING: "IfcStructuralLinearActionVarying",
    IFCSTRUCTURALLOAD: "IfcStructuralLoad",
    IFCSTRUCTURALLOADGROUP: "IfcStructuralLoadGroup",
    IFCSTRUCTURALLOADLINEARFORCE: "IfcStructuralLoadLinearForce",
    IFCSTRUCTURALLOADPLANARFORCE: "IfcStructuralLoadPlanarForce",
    IFCSTRUCTURALLOADSINGLEDISPLACEMENT: "IfcStructuralLoadSingleDisplacement",
    IFCSTRUCTURALLOADSINGLEDISPLACEMENTDISTORTION: "IfcStructuralLoadSingleDisplacementDistortion",
    IFCSTRUCTURALLOADSINGLEFORCE: "IfcStructuralLoadSingleForce",
    IFCSTRUCTURALLOADSINGLEFORCEWARPING: "IfcStructuralLoadSingleForceWarping",
    IFCSTRUCTURALLOADSTATIC: "IfcStructuralLoadStatic",
    IFCSTRUCTURALLOADTEMPERATURE: "IfcStructuralLoadTemperature",
    IFCSTRUCTURALMEMBER: "IfcStructuralMember",
    IFCSTRUCTURALPLANARACTION: "IfcStructuralPlanarAction",
    IFCSTRUCTURALPLANARACTIONVARYING: "IfcStructuralPlanarActionVarying",
    IFCSTRUCTURALPOINTACTION: "IfcStructuralPointAction",
    IFCSTRUCTURALPOINTCONNECTION: "IfcStructuralPointConnection",
    IFCSTRUCTURALPOINTREACTION: "IfcStructuralPointReaction",
    IFCSTRUCTURALPROFILEPROPERTIES: "IfcStructuralProfileProperties",
    IFCSTRUCTURALREACTION: "IfcStructuralReaction",
    IFCSTRUCTURALRESULTGROUP: "IfcStructuralResultGroup",
    IFCSTRUCTURALSTEELPROFILEPROPERTIES: "IfcStructuralSteelProfileProperties",
    IFCSTRUCTURALSURFACECONNECTION: "IfcStructuralSurfaceConnection",
    IFCSTRUCTURALSURFACEMEMBER: "IfcStructuralSurfaceMember",
    IFCSTRUCTURALSURFACEMEMBERVARYING: "IfcStructuralSurfaceMemberVarying",
    IFCSTRUCTUREDDIMENSIONCALLOUT: "IfcStructuredDimensionCallout",
    IFCSTYLEMODEL: "IfcStyleModel",
    IFCSTYLEDITEM: "IfcStyledItem",
    IFCSTYLEDREPRESENTATION: "IfcStyledRepresentation",
    IFCSUBCONTRACTRESOURCE: "IfcSubContractResource",
    IFCSUBEDGE: "IfcSubedge",
    IFCSURFACE: "IfcSurface",
    IFCSURFACECURVESWEPTAREASOLID: "IfcSurfaceCurveSweptAreaSolid",
    IFCSURFACEOFLINEAREXTRUSION: "IfcSurfaceOfLinearExtrusion",
    IFCSURFACEOFREVOLUTION: "IfcSurfaceOfRevolution",
    IFCSURFACESTYLE: "IfcSurfaceStyle",
    IFCSURFACESTYLELIGHTING: "IfcSurfaceStyleLighting",
    IFCSURFACESTYLEREFRACTION: "IfcSurfaceStyleRefraction",
    IFCSURFACESTYLERENDERING: "IfcSurfaceStyleRendering",
    IFCSURFACESTYLESHADING: "IfcSurfaceStyleShading",
    IFCSURFACESTYLEWITHTEXTURES: "IfcSurfaceStyleWithTextures",
    IFCSURFACETEXTURE: "IfcSurfaceTexture",
    IFCSWEPTAREASOLID: "IfcSweptAreaSolid",
    IFCSWEPTDISKSOLID: "IfcSweptDiskSolid",
    IFCSWEPTSURFACE: "IfcSweptSurface",
    IFCSWITCHINGDEVICETYPE: "IfcSwitchingDeviceType",
    IFCSYMBOLSTYLE: "IfcSymbolStyle",
    IFCSYSTEM: "IfcSystem",
    IFCSYSTEMFURNITUREELEMENTTYPE: "IfcSystemFurnitureElementType",
    IFCTSHAPEPROFILEDEF: "IfcTShapeProfileDef",
    IFCTABLE: "IfcTable",
    IFCTABLEROW: "IfcTableRow",
    IFCTANKTYPE: "IfcTankType",
    IFCTASK: "IfcTask",
    IFCTELECOMADDRESS: "IfcTelecomAddress",
    IFCTENDON: "IfcTendon",
    IFCTENDONANCHOR: "IfcTendonAnchor",
    IFCTERMINATORSYMBOL: "IfcTerminatorSymbol",
    IFCTEXTLITERAL: "IfcTextLiteral",
    IFCTEXTLITERALWITHEXTENT: "IfcTextLiteralWithExtent",
    IFCTEXTSTYLE: "IfcTextStyle",
    IFCTEXTSTYLEFONTMODEL: "IfcTextStyleFontModel",
    IFCTEXTSTYLEFORDEFINEDFONT: "IfcTextStyleForDefinedFont",
    IFCTEXTSTYLETEXTMODEL: "IfcTextStyleTextModel",
    IFCTEXTSTYLEWITHBOXCHARACTERISTICS: "IfcTextStyleWithBoxCharacteristics",
    IFCTEXTURECOORDINATE: "IfcTextureCoordinate",
    IFCTEXTURECOORDINATEGENERATOR: "IfcTextureCoordinateGenerator",
    IFCTEXTUREMAP: "IfcTextureMap",
    IFCTEXTUREVERTEX: "IfcTextureVertex",
    IFCTHERMALMATERIALPROPERTIES: "IfcThermalMaterialProperties",
    IFCTIMESERIES: "IfcTimeSeries",
    IFCTIMESERIESREFERENCERELATIONSHIP: "IfcTimeSeriesReferenceRelationship",
    IFCTIMESERIESSCHEDULE: "IfcTimeSeriesSchedule",
    IFCTIMESERIESVALUE: "IfcTimeSeriesValue",
    IFCTOPOLOGICALREPRESENTATIONITEM: "IfcTopologicalRepresentationItem",
    IFCTOPOLOGYREPRESENTATION: "IfcTopologyRepresentation",
    IFCTRANSFORMERTYPE: "IfcTransformerType",
    IFCTRANSPORTELEMENT: "IfcTransportElement",
    IFCTRANSPORTELEMENTTYPE: "IfcTransportElementType",
    IFCTRAPEZIUMPROFILEDEF: "IfcTrapeziumProfileDef",
    IFCTRIMMEDCURVE: "IfcTrimmedCurve",
    IFCTUBEBUNDLETYPE: "IfcTubeBundleType",
    IFCTWODIRECTIONREPEATFACTOR: "IfcTwoDirectionRepeatFactor",
    IFCTYPEOBJECT: "IfcTypeObject",
    IFCTYPEPRODUCT: "IfcTypeProduct",
    IFCUSHAPEPROFILEDEF: "IfcUShapeProfileDef",
    IFCUNITASSIGNMENT: "IfcUnitAssignment",
    IFCUNITARYEQUIPMENTTYPE: "IfcUnitaryEquipmentType",
    IFCVALVETYPE: "IfcValveType",
    IFCVECTOR: "IfcVector",
    IFCVERTEX: "IfcVertex",
    IFCVERTEXBASEDTEXTUREMAP: "IfcVertexBasedTextureMap",
    IFCVERTEXLOOP: "IfcVertexLoop",
    IFCVERTEXPOINT: "IfcVertexPoint",
    IFCVIBRATIONISOLATORTYPE: "IfcVibrationIsolatorType",
    IFCVIRTUALELEMENT: "IfcVirtualElement",
    IFCVIRTUALGRIDINTERSECTION: "IfcVirtualGridIntersection",
    IFCWALL: "IfcWall",
    IFCWALLSTANDARDCASE: "IfcWallStandardCase",
    IFCWALLTYPE: "IfcWallType",
    IFCWASTETERMINALTYPE: "IfcWasteTerminalType",
    IFCWATERPROPERTIES: "IfcWaterProperties",
    IFCWINDOW: "IfcWindow",
    IFCWINDOWLININGPROPERTIES: "IfcWindowLiningProperties",
    IFCWINDOWPANELPROPERTIES: "IfcWindowPanelProperties",
    IFCWINDOWSTYLE: "IfcWindowStyle",
    IFCWORKCONTROL: "IfcWorkControl",
    IFCWORKPLAN: "IfcWorkPlan",
    IFCWORKSCHEDULE: "IfcWorkSchedule",
    IFCZSHAPEPROFILEDEF: "IfcZShapeProfileDef",
    IFCZONE: "IfcZone"
};